### ISSUE TITLE
More thymidine modifications

### ISSUE THREAD

**Issue by pweigele** [hoffmangroup/dnamod#5]
Hi there,

I don't know if you consider the intermediates in DNA hypermodification to be bona fide modifications, but herein are described six new modifications, all of them enzymatically produced and stable in vitro under physiological conditions. One of these is 5-acetylaminomethyl-2'-deoxyuridine (5-acNmdU), and is the end product of a newly discovered pathway related to 5-NedU biosynthesis in phage M6 and related.

https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkab781/6370258

Best,
Peter

**Comment by cviner** [comment]
Hi Peter,

We indeed do not, and consider such intermediates beyond the scope of DNAmod. We have additionally ceased regular updates to our database.

Nonetheless, this is quite interesting work and we appreciate your bringing it to our attention!

Best regards,

Coby

**Comment by pweigele** [comment]
Hi Coby,

One of those mods is a final product, and therefore would have been a candidate for your database. But I am sorry to hear that DNAmod is not being updated regularly. The field is growing, with many new chemistries, enzymes, and biological functions being discovered. Hopefully someone will pick it up in the future. 

Best wishes,
Peter

**Comment by cviner** [comment]
Hi Peter,

Yes, I did indeed appreciate that!

I agree—we simply don't have the resources to continue, with my needing to move on to other projects, after having maintained it for a number of years after publication.

That said, I too think it would be nice for someone to keep it updated; we would be open to potential collaboration on that front, if anyone external to our group ever expresses interest in taking over its maintainer-ship.

Many thanks,

Coby
